-- init_admin_user.sql - Create Admin User Table and Default Admin

-- Create ADMIN_USERS table
CREATE TABLE IF NOT EXISTS ADMIN_USERS (
    USER_ID INT PRIMARY KEY AUTO_INCREMENT,
    USERNAME VARCHAR(50) UNIQUE NOT NULL,
    PASSWORD VARCHAR(100) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Insert default admin user (username: admin, password: admin123)
INSERT INTO ADMIN_USERS (USERNAME, PASSWORD) 
VALUES ('admin', 'admin123')
ON DUPLICATE KEY UPDATE USERNAME=USERNAME;

-- Verify
SELECT * FROM ADMIN_USERS;
